### ISSUE TITLE
Invalid Signature on useSignAndExecuteTransaction

### ISSUE THREAD

**Issue by Dangujba** [MystenLabs/sui#20734] opened 2024-12-24 22:49 UTC
When i try to execute the function signAndExecuteTransaction i am getting this error
Transaction Failed
Invalid user signature: Signature is not valid: ZKLogin max epoch too large 596, current epoch 26, max accepted: 56

```
const suiTransaction = async () => {
      if (!walletAddress || !amount || !network) {
          Swal.fire({
              icon: 'error',
              title: 'Missing Information',
              text: 'Wallet address, amount, or network is missing.',
          });
          return;
      }

      try {
          // Confirm the transaction details with the user
          bootbox.confirm({
              title: "Confirm Transaction",
              message: `
                  <p><strong>Coin:</strong> ${coinName}</p>
                  <p><strong>Network:</strong> ${network}</p>
                  <p><strong>Amount:</strong> ${amount} ${coinName}</p>
                  <p><strong>Price:</strong> ${formatPrice(price)}</p>
                  <p>Are you sure you want to proceed?</p>
              `,
              buttons: {
                  confirm: {
                      label: 'Yes, send it!',
                      className: 'btn-success',
                  },
                  cancel: {
                      label: 'No, cancel',
                      className: 'btn-danger',
                  },
              },
              callback: async (result) => {
                  if (result) {
                      // Show a loading indicator
                      Swal.fire({
                          title: 'Processing Transaction...',
                          text: 'Please wait while the transaction is being processed.',
                          allowOutsideClick: false,
                          showConfirmButton: false,
                          willOpen: () => {
                              Swal.showLoading();
                          },
                      });

                      try {
                          
                          const tx = new Transaction();
                          const [coin] = tx.splitCoins(tx.gas, [5000000]);
                          tx.transferObjects([coin], walletAddress);
                           
                          const result = await signAndExecuteTransaction({
                              transaction: tx,
                              chain: "sui:testnet", \
                            
                          });

                          // Success feedback
                          Swal.fire({
                              icon: 'success',
                              title: 'Transaction Successful',
                              html: `
                                  <p><strong>Transaction Digest:</strong> ${result.digest}</p>
                                  <p><strong>Amount Sent:</strong> ${amount} ${coinName}</p>
                                  <p><strong>Price:</strong> $${price}</p>
                              `,
                          });
                          console.log('Transaction Result:', result);
                      } catch (error) {
                          // Show error feedback
                          Swal.fire({
                              icon: 'error',
                              title: 'Transaction Failed',
                              text: error.message || 'An error occurred during the transaction.',
                          });
                          console.error('Transaction Error:', error);
                      }
                  }
              },
          });
      } catch (error) {
          // Show error feedback for unexpected issues
          Swal.fire({
              icon: 'error',
              title: 'Error',
              text: error.message || 'An unexpected error occurred.',
          });
      }
  };
```
i am using localhost (For more clarification)

**Comment by stefan-mysten** [comment] 2024-12-25 00:02
Duplicate of #20733

**Closed by stefan-mysten** 2024-12-25 00:02 UTC
Labels: doc-issue
