### ISSUE TITLE
[fullnode] Synchronization problem if lack of memory

### ISSUE THREAD

**Issue by Nelrann** [MystenLabs/sui#3460] opened 2022-07-25 11:43 UTC
## Steps to Reproduce Issue

Start a full node with docker and limit resource to 8Go

## Expected Result

According to the documentation, a fullnode should sync with 8Go 
https://docs.sui.io/build/fullnode#hardware-requirements

## Actual Result

Fullnode  stops syncing when there are no more resources available

## System Information

* OS: 20.04

![2](https://user-images.githubusercontent.com/503587/180769724-1b39d9a6-0641-4358-91a0-54e591976a87.png)
![1](https://user-images.githubusercontent.com/503587/180769726-191a0f9b-dc65-4593-b5bf-2954ab01b8a6.png)

**Comment by mindstyle85** [comment] 2022-07-25 12:19
we can confirm theres a memory leak or a race condition here, our machine has 32gb RAM and its using all of it (98%)

**Comment by pops-one** [comment] 2022-07-25 12:19
we can confirm theres a memory leak or a race condition here, our machine has 32gb RAM and its using all of it (98%)

**Comment by pops-one** [comment] 2022-07-25 13:08
to update, the race condition we met is not from a new node, our node has been running for days and memory usage slowly increased

its on a dedicated 32gb ram, i7 and 1tb nvme ssd with 1gbps connection

using binaries with systemd on  Ubuntu 20.04.4 LTS

**Comment by Nelrann** [comment] 2022-07-25 15:10
CPU/Memory usage

![Capture](https://user-images.githubusercontent.com/503587/180812546-c80ee73d-2ee8-413d-a8c8-b1059a78c0ef.PNG)

**Comment by gdanezis** [comment] 2022-07-25 16:32
Many thanks for your bug report. We are looking into it.

**Comment by pops-one** [comment] 2022-07-25 16:42
Just a follow up, we restarted our systemd and as thought the RAM usage fell down significantly (6% utilization). Now after 3h or so, its crawled back to 38% utilization already, which is already over 8GB

**Comment by mystenmark** [comment] 2022-07-25 17:47
Thanks for the report, I believe I've reproduced the issue and should have a fix soon.

**Comment by mystenmark** [comment] 2022-07-26 03:45
There are a number of bug fixes in main right now that will be in the next release - among them will be #3489 which I think may have been the root cause of the problem you reported.

**Comment by Nelrann** [comment] 2022-07-26 07:45
thank you @mystenmark, I'm waiting for the changes to be on the devnet branch to give you feedback

**Comment by Nelrann** [comment] 2022-07-27 00:16
Following the last update, I wanted to update my fullnode to try the latest changes but I got this error:

`Error: Authority Error: "Checkpoint blocked by pending certificates`

**Comment by Nelrann** [comment] 2022-08-02 23:40
The latest updates seem to consume a lot of memory
![image](https://user-images.githubusercontent.com/503587/182494650-d1b96a9d-26a6-4994-b00b-3d6430ace072.png)

**Comment by Nelrann** [comment] 2022-08-08 01:19
several people had memory problems when synchronizing.
I just did a test again and it seems that the memory exceeds 8G.
this problem seems to happen as soon as there are more than 70K transactions to sync

![image](https://user-images.githubusercontent.com/503587/183320277-31ba4b17-c62c-453c-a970-d45fa95f7a82.png)

**Comment by Nelrann** [comment] 2022-08-08 01:21
@mystenmark @gdanezis
I just did a test again and it seems that the memory exceeds 8G.
this problem seems to happen as soon as there are more than 70K transactions to sync

![image](https://user-images.githubusercontent.com/503587/183320568-74c6d7ee-b6c6-4e78-8ba6-ff1f4cfd6ffb.png)

**Closed** 2023-12-27 04:24 UTC
Labels: sui-node
