### ISSUE TITLE
wallet-standard call adapter's disconnect method in react provider

### ISSUE THREAD

**Issue by younessyk** [MystenLabs/sui#5375] opened 2022-10-19 11:31 UTC
Steps to Reproduce Issue
Seems your team forget to call adapter's disconnect method in the react provider:

https://github.com/MystenLabs/sui/blob/main/sdk/wallet-adapter/packages/react-providers/src/WalletContext.tsx#L75

Expected Result
react provider can trigger the adapter's disconnect method.

Actual Result
react provider does not trigger the adapter's disconnect method.

System Information
OS:
Compiler:

**Comment by Jordan-Mysten** [comment] 2022-10-21 01:15
Duplicate of #5178

**Closed by Jordan-Mysten** 2022-10-21 01:15 UTC
