### ISSUE TITLE
[BUG]: CLI - Binaries (1.7.0) MainNet (1.6.3)

### ISSUE THREAD

**Issue by FrankC01** [MystenLabs/sui#13380] opened 2023-08-12 12:27 UTC
## Steps to Reproduce Issue

**Setup a mainnet environment via CLI**

Run:

`sui client gas 0x4a58765fdf12b0467fe68fa66d1e2b3d26bc13ed26ac00df053ddbf044b5bc09`

## Expected Result

Expected listing of gas objects

## Actual Result

Result:
```bash
RPC call failed: ErrorObject { code: ServerError(-32000), message: "Index store not available on this Fullnode.", data: None }

Caused by:
    RPC call failed: ErrorObject { code: ServerError(-32000), message: "Index store not available on this Fullnode.", data: None }
```

**Comment by mehran636311** [comment] 2023-08-13 14:21
Ok

**Comment by uvd** [comment] 2023-08-14 13:42
RPC: https://fullnode.mainnet.sui.io/ 

request
```json
{"jsonrpc":"2.0","id":"0","method":"suix_getDynamicFields","params":["0x49136005e90e28c4695419ed4194cc240603f1ea8eb84e62275eaff088a71063",null,null]}
```



response
```json
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32000,
        "message": "Index store not available on this Fullnode."
    },
    "id": "0"
}
```

```json
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32000,
        "message": "Index store not available on this Fullnode."
    },
    "id": 1
}
```

**Comment by 666lcz** [comment] 2023-08-14 16:14
@uvd @FrankC01 Thank you both for flagging this! This was caused by a configuration error and it should be fixed now. Could you re-check?

**Closed** 2023-08-14 16:14 UTC

**Comment by FrankC01** [comment] 2023-08-14 19:23
@666lcz 

Works fine for me!

**Comment by mehran636311** [comment] 2023-08-15 17:52
My wallet

**Comment by mehran636311** [comment] 2023-08-15 17:52
0x33b6f51abbf01665f3f30c737ad678509fbe2e95799fa64e54a960a80d0d1fbc
