### ISSUE TITLE
Sui CLI `sui client pay` unexpected results

### ISSUE THREAD

**Issue by FrankC01** [MystenLabs/sui#5351] opened 2022-10-18 08:47 UTC
## Steps to Reproduce Issue
Using fullnode devnet:

### 1. Coin/mists before
```bash
0x21adc6721699e03e8f7a1de4fb47eb4ea7ebb42a | 19780043
0x943750318a8305f1cb12007146fe40137e2d2593 | 10193864
0xd2c5c5c4cd4ae6f7d8defaf3567cb3174118aae0 | 9997137
0xd4601e8e59c08d81a21dac1877a3032c0f0e9cee | 10000000
```

### 2. Invoke pay
```bash
sui client pay --amounts 3 10000 --recipients 0xd2c5c5c4cd4ae6f7d8defaf3567cb3174118aae0 0xd4601e8e59c08d81a21dac1877a3032c0f0e9cee --input-coins 0x21adc6721699e03e8f7a1de4fb47eb4ea7ebb42a --gas 0x943750318a8305f1cb12007146fe40137e2d2593 --gas-budget 1000
```
## Expected Result
```bash
0x21adc6721699e03e8f7a1de4fb47eb4ea7ebb42a | 19770040
0x943750318a8305f1cb12007146fe40137e2d2593 | 10192864
0xd2c5c5c4cd4ae6f7d8defaf3567cb3174118aae0 | 9997140
0xd4601e8e59c08d81a21dac1877a3032c0f0e9cee | 10010000
```

## Actual Result
```bash
0x21adc6721699e03e8f7a1de4fb47eb4ea7ebb42a | 19770040
0x943750318a8305f1cb12007146fe40137e2d2593 | 10193781
0xd2c5c5c4cd4ae6f7d8defaf3567cb3174118aae0 | 9997137
0xd4601e8e59c08d81a21dac1877a3032c0f0e9cee | 10000000
```
## System Information

* OS: macOS Monterey 12.6 (M1 Max)
* Sui binary 0.11.0

**Comment by 666lcz** [comment] 2022-10-18 14:45
@FrankC01 This is not a bug. Note that addresses and object IDs can be the same. In this case, you are transferring 3 SUI to the address `0xd2c5c5c4cd4ae6f7d8defaf3567cb3174118aae0` (https://explorer.devnet.sui.io/addresses/0xd2c5c5c4cd4ae6f7d8defaf3567cb3174118aae0) and 10000 to the address `0xd4601e8e59c08d81a21dac1877a3032c0f0e9cee`(https://explorer.devnet.sui.io/addresses/0xd4601e8e59c08d81a21dac1877a3032c0f0e9cee). What your command(`sui client gas`) shows is the balances of the gas object `0xd2c5c5c4cd4ae6f7d8defaf3567cb3174118aae0` (https://explorer.devnet.sui.io/objects/0xd2c5c5c4cd4ae6f7d8defaf3567cb3174118aae0) and `0xd4601e8e59c08d81a21dac1877a3032c0f0e9cee`(https://explorer.devnet.sui.io/objects/0xd4601e8e59c08d81a21dac1877a3032c0f0e9cee).

**Closed by 666lcz** 2022-10-18 14:45 UTC

**Comment by FrankC01** [comment] 2022-10-18 18:20
@666lcz  I don't get it. The addresses I showed in the issue are gas object IDs no? And the before and after (both real and what I expected) are not showing the distribution I thought would have happened?

Could you provide a better explanation?

**Comment by FrankC01** [comment] 2022-10-19 19:31
AHA! I just realized that what you were saying is that the recipients are ADDRESSES and not other coin types.
