### ISSUE TITLE
Running `sui move test` inside VSCode terminal does not respond

### ISSUE THREAD

**Issue by parklife2023** [MystenLabs/sui#18983] opened 2024-08-14 05:59 UTC
## Steps to Reproduce Issue

Use the terminal of vscode to execute "sui move test", and there will be no response, but other commands will respond. In addition, if you turn off vscode, you can use the built-in cmd of Windows to execute it. If vscode is open, you can execute "sui move test" in the same way. No response

## Expected Result

The result of compiler should be run out.

## Actual Result

Nothing happens, but if I turn off vscode at this time, it can run

## System Information

OS: windows 10
Terminal using vscode (1.92.1)

**Comment by stefan-mysten** [comment] 2024-08-14 14:54
Thanks for reporting this @parklife2023. This is really useful! 
Could you also share the Sui CLI version: `sui -V` and maybe the `Move.toml` file, if it is not confidential?

**Comment by awelc** [comment] 2024-08-14 15:10
Closing as a duplicate of https://github.com/MystenLabs/sui/issues/18749 (please follow https://github.com/MystenLabs/sui/issues/18749 for progress updates)

**Closed by awelc** 2024-08-14 15:10 UTC
Labels: vscode-move-plugin

**Comment by parklife2023** [comment] 2024-08-14 21:28
Thank you for reply.
Sui CLI version: 
sui 1.30.1-a4185da5659d

Move.toml
[package]
name = "lesson1"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
# license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
# authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

# For remote import, use the `{ git = "...", subdir = "...", rev = "..." }`.
# Revision can be a branch, a tag, and a commit hash.
# MyRemotePackage = { git = "https://some.remote/host.git", subdir = "remote/path", rev = "main" }

# For local dependencies use `local = path`. Path is relative to the package root
# Local = { local = "../path/to" }

# To resolve a version conflict and force a specific version for dependency
# override use `override = true`
# Override = { local = "../conflicting/version", override = true }

[addresses]
lesson1 = "0x0"

# Named addresses will be accessible in Move as `@name`. They're also exported:
# for example, `std = "0x1"` is exported by the Standard Library.
# alice = "0xA11CE"

[dev-dependencies]
# The dev-dependencies section allows overriding dependencies for `--test` and
# `--dev` modes. You can introduce test-only dependencies here.
# Local = { local = "../path/to/dev-build" }

[dev-addresses]
# The dev-addresses section allows overwriting named addresses for the `--test`
# and `--dev` modes.
# alice = "0xB0B"

**Comment by awelc** [comment] 2024-08-14 22:13
Thank you for this, but let's consolidate further discussion in  https://github.com/MystenLabs/sui/issues/18749

**Comment by awelc** [comment] 2024-08-15 21:13
Should be fixed in VSCode v1.0.11. Please re-install the extension and all should be good
