### ISSUE TITLE
Sui doc content issue or request

### ISSUE THREAD

**Issue by kabnureshivshankar** [MystenLabs/sui#7861] opened 2023-01-29 21:35 UTC
we cant find the options for testing in the app after launce of wave 2 on laptop but those options visible in the phone.

**Comment by kabnureshivshankar** [comment] 2023-01-29 21:35
we cant find the options for testing in the app after launce of wave 2 on laptop but those options visible in the phone

**Comment by georgescharlesbrain** [comment] 2023-01-30 04:30
Duplicate of #7866

**Closed** 2023-01-30 16:55 UTC
Labels: doc-issue
