### ISSUE TITLE
[RPC Server] CORS is not working properly

### ISSUE THREAD

**Issue by 666lcz** [MystenLabs/sui#1597] opened 2022-04-26 20:14 UTC
![corsError](https://user-images.githubusercontent.com/76067158/165383849-0da238f9-ff24-4279-b7ee-c4d48cb4958f.png)
![corsNetwork](https://user-images.githubusercontent.com/76067158/165383860-4b21dc84-6fd5-4f72-9bd3-b9b4a6770618.png)

@Andrew47 encountered the above error when trying to send request to RPC server on DevNet through the Explorer frontend. The deployed instance should have `ACCESS_CONTROL_ALLOW_ORIGIN` set to `*` https://github.com/MystenLabs/sui-operations/pull/12/files#r857979777

I was able to reproduce the error on a local RPC server by using https://github.com/njgibbon/nicks-cors-test

**Comment by 666lcz** [comment] 2022-04-26 20:27
These might be helpful but I haven't gotten the chance to take a close look:
- [jsonrpsee preflight](https://github.com/paritytech/jsonrpsee/blob/e6c6ac58a182930f7aaf304395b2eb664c7eecc5/tests/tests/integration_tests.rs#L620)
- https://github.com/MystenLabs/sui/pull/893

**Comment by patrickkuo** [comment] 2022-04-26 21:59
The acl config is set correctly in jsonrpsee server, could be a jsonrpsee bug… I will investigate

**Comment by patrickkuo** [comment] 2022-04-26 22:48
Looking at the code, jsonrpsee only returns `ACCESS_CONTROL_ALLOW_ORIGIN` header if `Origin` is not equals to `host`
Do we set the `Origin` header in the request, it will not return the flag if `Origin` is not set.

https://github.com/paritytech/jsonrpsee/blob/e6c6ac58a182930f7aaf304395b2eb664c7eecc5/http-server/src/server.rs#L439-L451

**Comment by patrickkuo** [comment] 2022-04-26 23:07
I tried with postman with added Origin header and it works fine
<img width="2056" alt="image" src="https://user-images.githubusercontent.com/1888654/165407075-20aff249-c14c-4a95-9e0e-0209f9eee956.png">

I tried https://github.com/njgibbon/nicks-cors-test, it doesn't work because somehow all my browsers are not setting the Origin header :|

**Comment by 666lcz** [comment] 2022-04-26 23:11
@patrickkuo postman should work even without setting `Origin` right? cc @arun-koshy @stella3d @Andrew47  for any insights

**Comment by arun-koshy** [comment] 2022-04-26 23:15
Correct, CORS is a server side configuration and clients decide to enforce it or not. Development tools like Postman don't care about this so they don't enforce it. Browsers do, which is why you should that exclusively for testing CORS.

**Comment by patrickkuo** [comment] 2022-04-26 23:30
> insights

Yes postman will work regardless of CORS, but I am looking at the return header from the server, it does have the ACCESS_CONTROL_ALLOW_ORIGIN header set

**Comment by arun-koshy** [comment] 2022-04-26 23:39
I did some quick digging but maybe the correct behavior is to not have it set if you want any `Origin` to be allowed?

[set_allowed_orgins doc comments](https://github.com/paritytech/jsonrpsee/blob/2f5fef24534b96a0827d519664d601ba861361a5/ws-server/src/server.rs#L722) seem to indicate this and binary code seems to show that it is set via an environment variable which is what I assume you are setting when you launch the RPC server?

**Comment by patrickkuo** [comment] 2022-04-27 08:59
> I did some quick digging but maybe the correct behavior is to not have it set if you want any `Origin` to be allowed?
> 
> [set_allowed_orgins doc comments](https://github.com/paritytech/jsonrpsee/blob/2f5fef24534b96a0827d519664d601ba861361a5/ws-server/src/server.rs#L722) seem to indicate this and[ binary code](https://github.com/MystenLabs/sui/blob/96611e00df74146d73567b6731514dfb5b1a543c/sui/src/bin/rpc-server.rs#L63) seems to show that it is set via an environment variable which is what I assume you are setting when you launch the RPC server?

Ah you are looking at the Websocket implementation, we are using the HTTP server

**Comment by patrickkuo** [comment] 2022-04-27 10:57
@666lcz can you try setting the `Origin` header in the request and see if that works? I couldn't get explorer to run locally so can't confirm if this works. (getting bunch of `Module not found: Error: Can't resolve 'sui.js'`)

Looks like geth is behaving the same way https://ethereum.stackexchange.com/questions/10622/why-is-access-control-allow-origin-not-in-the-response-headers

**Comment by 666lcz** [comment] 2022-04-28 03:27
@Andrew47  I have trouble compiling `explore-rpc` as well. I have tried `yarn && yarn build && npm link` under `src/sdk/typescript` as well as `npm link sui.js && yarn && yarn start`. However, it's complaining

```
Attempted import error: 'isObjectExistsInfo' is not exported from 'sui.js' (imported as 'isObjectExistsInfo').
ERROR in ./src/components/ownedobjects/OwnedObjects.tsx 73:42-60
export 'isObjectExistsInfo' (imported as 'isObjectExistsInfo') was not found in 'sui.js' (possible exports: BCS, Base64DataBuffer, Ed25519Keypair, HexDataBuffer, JsonRpcProvider, PUBLIC_KEY_SIZE, Provider, PublicKey, RawSigner, RpcTxnDataSerializer, SignerWithProvider)

ERROR in ./src/components/ownedobjects/OwnedObjects.tsx 83:43-54
export 'isObjectRef' (imported as 'isObjectRef') was not found in 'sui.js' (possible exports: BCS, Base64DataBuffer, Ed25519Keypair, HexDataBuffer, JsonRpcProvider, PUBLIC_KEY_SIZE, Provider, PublicKey, RawSigner, RpcTxnDataSerializer, SignerWithProvider)

ERROR in ./src/pages/object-result/ObjectLoaded.tsx 85:7-25
export 'isObjectExistsInfo' (imported as 'isObjectExistsInfo') was not found in 'sui.js' (possible exports: BCS, Base64DataBuffer, Ed25519Keypair, HexDataBuffer, JsonRpcProvider, PUBLIC_KEY_SIZE, Provider, PublicKey, RawSigner, RpcTxnDataSerializer, SignerWithProvider)

ERROR in ./src/pages/object-result/ObjectResult.tsx 31:9-32
export 'isGetObjectInfoResponse' (imported as 'isGetObjectInfoResponse') was not found in 'sui.js' (possible exports: BCS, Base64DataBuffer, Ed25519Keypair, HexDataBuffer, JsonRpcProvider, PUBLIC_KEY_SIZE, Provider, PublicKey, RawSigner, RpcTxnDataSerializer, SignerWithProvider)

ERROR in ./src/pages/transaction-result/TransactionResult.tsx 108:6-28
export 'isCertifiedTransaction' (imported as 'isCertifiedTransaction') was not found in 'sui.js' (possible exports: BCS, Base64DataBuffer, Ed25519Keypair, HexDataBuffer, JsonRpcProvider, PUBLIC_KEY_SIZE, Provider, PublicKey, RawSigner, RpcTxnDataSerializer, SignerWithProvider)

ERROR in ./src/pages/transaction-result/TransactionResult.tsx 115:35-58
export 'isSingleTransactionKind' (imported as 'isSingleTransactionKind') was not found in 'sui.js' (possible exports: BCS, Base64DataBuffer, Ed25519Keypair, HexDataBuffer, JsonRpcProvider, PUBLIC_KEY_SIZE, Provider, PublicKey, RawSigner, RpcTxnDataSerializer, SignerWithProvider)

ERROR in ./src/pages/transaction-result/TransactionResult.tsx 118:36-46
export 'isTransfer' (imported as 'isTransfer') was not found in 'sui.js' (possible exports: BCS, Base64DataBuffer, Ed25519Keypair, HexDataBuffer, JsonRpcProvider, PUBLIC_KEY_SIZE, Provider, PublicKey, RawSigner, RpcTxnDataSerializer, SignerWithProvider)

ERROR in ./src/pages/transaction-result/TransactionResult.tsx 123:32-42
export 'isMoveCall' (imported as 'isMoveCall') was not found in 'sui.js' (possible exports: BCS, Base64DataBuffer, Ed25519Keypair, HexDataBuffer, JsonRpcProvider, PUBLIC_KEY_SIZE, Provider, PublicKey, RawSigner, RpcTxnDataSerializer, SignerWithProvider)

ERROR in ./src/pages/transaction-result/TransactionResult.tsx 127:35-54
export 'isMoveModulePublish' (imported as 'isMoveModulePublish') was not found in 'sui.js' (possible exports: BCS, Base64DataBuffer, Ed25519Keypair, HexDataBuffer, JsonRpcProvider, PUBLIC_KEY_SIZE, Provider, PublicKey, RawSigner, RpcTxnDataSerializer, SignerWithProvider)

webpack compiled with 9 errors
Files successfully emitted, waiting for typecheck results...
Issues checking in progress...
```

Not sure why since `index.ts` is exporting everything from `index.guard.ts` cc @stella3d

**Comment by 666lcz** [comment] 2022-04-28 03:29
Also, surprisingly in the demo app: https://github.com/MystenLabs/sdk-test-app, which is also browser based and uses the SDK, there's no CORS issue when making a request to the Devnet

**Comment by Andrew47** [comment] 2022-04-28 12:50
@666lcz --> It looks like the issue is that `index.ts` is not exporting everything from `index.guard.ts`. I could not find the following in the `index.ts` file:

```js
export * from 'index.guard'
```

**Comment by Andrew47** [comment] 2022-04-28 13:15
It looks like we're no longer getting CORS errors in the SuiExplorer UI:

![image](https://user-images.githubusercontent.com/11377188/165760194-5715d8f1-3766-4b66-9ca6-453b46dc0632.png)

This corroborates with what @666lcz identified with the demo app. 

Many thanks to whomever updated the API to resolve this issue.

 Perhaps we can now close this issue as resolved?

**Closed** 2022-04-29 00:31 UTC
Labels: tools
