### ISSUE TITLE
Trying to run a node following the official documentation and it fails on recommended OS and hardware

### ISSUE THREAD

**Issue by raiym** [MystenLabs/sui#3810] opened 2022-08-06 10:22 UTC
Ubuntu 18.04 LTS and 32GB 8CPU publicly available IP address. 

Both docs are either incorrect or not up to date. 

Also I really didn't understand why you add additional step to fork your repo except to gain some number of forks? 

This is what I have tried to run the full node:

**Build from sources:**
Followed exactly as described here: 
https://docs.sui.io/build/fullnode 
and getting following error: 
```
error: failed to select a version for the requirement `phf = "^0.11"`
``` 
when i try to change the crate version to 0.10 in toml file getting following error:
```
error: failed to select a version for the requirement `serde_with = "^2"`
```

**Run with Docker:**
Okay with a thought that I don't want to waste any more time trying to understand why it does not work I switched to docker. 
And followed same exact steps: https://github.com/MystenLabs/sui/tree/main/docker/fullnode#readme 
And again it failed: 
```
ERROR: Version in "./docker-compose.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
```

So I danced around my laptop and got it work by installing newer version of docker-compose and finally something started moving. 

Now I executed: 

```
docker-compose up -d
```

And then curled to get the transactions as described in the doc: 

```
curl --location --request POST 'http://127.0.0.1:9000/' \
    --header 'Content-Type: application/json' \
    --data-raw '{ "jsonrpc":"2.0", "id":1, "method":"sui_getRecentTransactions", "params":[5] }'
```

And following printed:
```
curl: (56) Recv failure: Connection reset by peer

```

So what does this mean? Does it mean sync still in progress and I should wait? Or something is wrong with installation? 

Why even start marketing if this thing is not even half baked? Not sure how are you planning to attract regular developers if such basic things just not working.

**Comment by DaisukeYoda** [comment] 2022-08-07 08:16
Same issue here.

**Comment by liasica** [comment] 2022-08-07 09:43
Same issue

**Comment by huitseeker** [comment] 2022-08-07 15:35
This is probably an issue with installing rust. The repository is configured to work better with installations of the rust toolchain that is packages with [rustup](https://rustup.rs/).
Closing this as a duplicate of #3776 in order to centralize the discussion.

**Closed by huitseeker** 2022-08-07 15:35 UTC
Labels: duplicate

**Comment by raiym** [comment] 2022-08-07 22:53
What about this, installed with docker and getting: 

```
curl --location --request POST 'http://127.0.0.1:9000/'     --header 'Content-Type: application/json'     --data-raw '{ "jsonrpc":"2.0", "id":1, "method":"sui_getRecentTransactions", "params":[5] }'

curl: (56) Recv failure: Connection reset by peer
```

**Comment by gosi-at** [comment] 2022-08-07 23:32
Had the same issue with docker, for me this worked: go to the directory that hosts your docker-compose file and fullnode-template.yaml file and then:

sed -i 's/127.0.0.1/0.0.0.0/' fullnode-template.yaml

after that restart the containers.
