### ISSUE TITLE
Move Analyzer crashes when 2 modules in different packages have the same name

### ISSUE THREAD

**Issue by thounyy** [MystenLabs/sui#19275] opened 2024-09-09 13:09 UTC
## Steps to Reproduce Issue

Create two different move packages in the same directory. Open this directory in vscode (or similar) to run move extension by Mysten. Name a module in each of the package the same way. Open output channels and see crash.

1. get the latest move analyzer
2. `git clone https://github.com/gmove-io/kraken` 
3. checkout [this commit](https://github.com/gmove-io/kraken/commit/afa7a0e55b52e937768411f6bfed8d4b1f9ae2eb), `git checkout afa7a0e55b52e937768411f6bfed8d4b1f9ae2eb`
4. open `./packages/actions/tests/utils.move` and uncomment the module 
5. wait for it to crash

## Expected Result

Normal functioning.

## Actual Result

``` shell
thread '<unnamed>' panicked at external-crates/move/crates/move-analyzer/src/symbols.rs:1959:76:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Error - 2:59:05 PM] The Move server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 2:59:05 PM] Server process exited with signal SIGABRT.
```

## System Information

* OS: latest Fedora
* Compiler: sui 1.32.0-homebrew

**Comment by awelc** [comment] 2024-09-09 18:07
Thank you for the report! I know what the problem is and working on a fix

**Comment by awelc** [comment] 2024-09-09 21:23
A bit more info on this. While `move-analyzer` crashing on this code is obviously bad (and I will do my best to fix it) the code itself is not quite correct either. Move build system disallows creating modules with the same name if they belong to a package with the same address. In this case, both `test_utils` modules are created in packages which have the same address (`0x0`) assigned. All is good if you build this code with `sui move build` as both these modules are test-only and would be excluded, but if you try `sui move test` you will see the following error:
```shell
error[E02001]: duplicate declaration, item, or annotation
  ┌─ ./../multisig/tests/utils.move:2:25
  │
2 │ module kraken_multisig::test_utils;
  │                         ^^^^^^^^^^ Duplicate definition for module '(kraken_multisig=0x0)::test_utils'
  │
  ┌─ ./tests/utils.move:2:24
  │
2 │ module kraken_actions::test_utils;
  │                        ---------- Module previously defined here, with '(kraken_actions=0x0)::test_utils'

```

As a side note, `move-analyzer` compiles all packages in test mode, so even after I fix the crash, our VSCode extension will report the error you see above

**Comment by thounyy** [comment] 2024-09-10 17:26
Oh yes that makes sense, I renamed them. Thanks for the help!

**Comment by awelc** [comment] 2024-09-10 23:20
A fix for this to prevent `move-analyzer` from crashing has been implemented in https://github.com/MystenLabs/sui/pull/19285 and the new version of the extension has been published to VSCode Marketplace (https://marketplace.visualstudio.com/items?itemName=mysten.move&ssr=false#overview)

**Closed by awelc** 2024-09-10 23:20 UTC
