### ISSUE TITLE
How to search for a list of NFTs of the same type？

### ISSUE THREAD

**Issue by e274426380** [MystenLabs/sui#6792] opened 2022-12-14 08:36 UTC
We have designed a function to register users to get NFTs containing user information, but we don't know how to target the user information by contract address and wallet address.
![image](https://user-images.githubusercontent.com/75345973/207546410-ffb09984-1ce9-4ac3-8865-15234d3d15a1.png)
I thought it would be a good option to get the same type of nft via this type, but didn't find a corresponding interface in the sdk.
Is there some problem?

**Comment by PaulFidika** [comment] 2022-12-14 21:59
I don't think there's any RPC call that let's you get all objects of a certain type. For example, I don't think you can query like 'get me all SUI coins in existence'. Once Sui has an indexer this will be an easy query however.

What you could do instead is broadcast an event, and then query the events:

https://docs.sui.io/sui-jsonrpc#sui_getEvents
https://docs.sui.io/build/event_api#event-filters

I.e., broadcast an event with the object-id every time you create an 'nft' type, and then query that. Event queries are paginated as well, so you don't have to worry about getting 100,000 results in one response lol.

**Comment by PaulFidika** [comment] 2022-12-14 22:01
To the Mysten team; is there an issue or pull request somewhere for something like 'sui_getObjectsOfType'? Would be a useful query to have.

**Comment by e274426380** [comment] 2022-12-15 08:41
> I don't think there's any RPC call that let's you get all objects of a certain type. For example, I don't think you can query like 'get me all SUI coins in existence'. Once Sui has an indexer this will be an easy query however.
> 
> What you could do instead is broadcast an event, and then query the events:
> 
> https://docs.sui.io/sui-jsonrpc#sui_getEvents https://docs.sui.io/build/event_api#event-filters
> 
> I.e., broadcast an event with the object-id every time you create an 'nft' type, and then query that. Event queries are paginated as well, so you don't have to worry about getting 100,000 results in one response lol.

I tried the getEvents interface.
This interface seems to work for my needs, but why does it report an error once I add 2 query conditions to the query parameter?
```
Error: Error getting events for query: Error: RPC Error: expected value at line 1 column 86 for query [object Object]
    at JsonRpcProvider.getEvents (json-rpc-provider.ts:680:13)
```
Is it that only 1 query condition is supported?

**Comment by patrickkuo** [comment] 2022-12-15 08:44
related: https://github.com/MystenLabs/sui/issues/6370

**Comment by amnn** [comment] 2022-12-15 08:45
Adding @patrickkuo who might have insight into the questions about potential new APIs and how the eventing API works as well.

**Comment by patrickkuo** [comment] 2022-12-15 08:49
> Is it that only 1 query condition is supported?

Currently we only support 1 query, we have plan to add query combination, but because we are moving the event store to indexer, this will happen after that.
https://github.com/MystenLabs/sui/issues/5501

**Comment by e274426380** [comment] 2022-12-15 08:56
@patrickkuo OK, thank you for your answer.
PaulFidika makes a good point, it would be nice to have the `sui_getObjectsByType` interface.

**Comment by patrickkuo** [comment] 2022-12-15 09:43
> @patrickkuo OK, thank you for your answer.
> PaulFidika makes a good point, it would be nice to have the `sui_getObjectsByType` interface.
ya agree, after the `getDynamicFields` [PR](https://github.com/MystenLabs/sui/pull/5882) is merged, I will update `sui_getObjectOwnedByAddress` and add optional Type query and pagination support.

**Comment by e274426380** [comment] 2022-12-15 09:45
@patrickkuo Looking forward to your updates

**Comment by PaulFidika** [comment] 2022-12-20 08:00
> > @patrickkuo OK, thank you for your answer.
> > PaulFidika makes a good point, it would be nice to have the `sui_getObjectsByType` interface.
> 
> ya agree, after the `getDynamicFields` [PR](https://github.com/MystenLabs/sui/pull/5882) is merged, I will update `sui_getObjectOwnedByAddress` and add optional Type query and pagination support.

No the real question is: can you search for ALL objects of the specified type, and return that? Not just the objects of Type T that are owned by an address, but all objects of Type T in Sui?

This is a complex question and query, because Type T's could be anywhere, depending on their abilities: (1) owned, (2) stored in a struct or dynamic field, or (3) shared / frozen?

For the NFT standard that we're building, NFTs will mostly be stored inside of a shared object. This will make them very easy to use, but the problem is: how do you find all of these shared objects?

This might be more of an indexer issue, but I'd prefer to be able to handle it all on the Fullnodes alone, if possible.

Specifically, could you build a fullnode query like `sui_getSharedObjectsByType` that returns all shared objects of type `NFTContainer<T>`?

If these containers were stored elsewhere, that would make them harder to find, but since they're all root-level objects, with UIDs, they should be easier to find. This will require Fullnodes to maintain an secondary index of root-level objects, indexed by type, in addition to being indexed by owner (which I'm assuming is the current primary index).

**Comment by PaulFidika** [comment] 2022-12-20 08:05
Also you should note that going forward, most objects in Sui will not be owned objects, but will be shared objects with an owner-field in their struct that gates who can access them.

For example, you can have a Safe (shared object) that allows authorized people to withdraw a specified amount of money from you, but you still 'own' that shared object because you have your address written in an 'owner' field. (Or, in a more complex pattern, you own a safe_capability which accomplishes the same thing.)

This creates an additional complexity; how do you find objects you own, but that are shared objects? For display in your wallet, perhaps. I don't have an easy answer; again, probably requires an indexer, but it's something to think about going forward.

**Comment by patrickkuo** [comment] 2022-12-20 13:08
Ok I see, what we want is an end point to get all existing objects of a specific type regardless of owner.

We will need a new index to retrieve this data efficiently, we are working on a new indexer and planning to move all indexing from full node to the indexer (indexer node?), this will be part of the indexer work. 

cc @gegaowp

**Closed** 2023-12-27 01:39 UTC
Labels: doc-issue
