### ISSUE TITLE
Sui Code Bug or Feature Request sui wallet zero balance 

### ISSUE THREAD

**Issue by Starlew77** [MystenLabs/sui#5613] opened 2022-10-27 18:01 UTC
## Steps to Reproduce Issue

sui wallet error message coins disappeared now zero balance 
https://ethoswallet.github.io/2048-demo/

Further to my previous bug i  have now achieved higher score but when i went to mint and link to sui wallet its taken all coins in wallet  and come up with this error message which was over 2million coins now zero balance which were in wallet and i now got this error message in wallet zero balance and no minted achievement from high score  please see attached photos 

e.g.
1. Call function <function call>.
2. Use return value and call <other function call>.

## Expected Result

Specify what outcome you expected should have resulted, but didn't.

minted reward :) for high score 

e.g.
Expected <other function call> to return 42.

coins still in wallet 

## Actual Result

Specify what the actual unexpected outcome was.

error message and now zero balance of coins 

e.g.
<other function call> returned 41.

## System Information

* OS: <specify OS version>
* Compiler: <specify compiler version>
![20221027_184842](https://user-images.githubusercontent.com/116558527/198364264-5f298ce7-474e-4cec-bc8d-6
![20221027_184851](https://us
![20221027_184909](https://user-images.githubusercontent.com/116558527/198364325-ac21b977-fc07-4b68-b523-27b71a3b2934.jpg)
er-images.githubusercontent.com/116558527/198364290-e96169ef-2cce-4d56-a9a6-a0c1d17e62f3.jpg)
9b0134db83b.jpg)

**Comment by Starlew77** [comment] 2022-10-27 18:02
![20221027_184851](https://user-images.githubusercontent.com/116558527/198364902-92b95f63-a37e-404b-bad2-1bbfa403692a.jpg)
![20221027_184842](https://user-images.githubusercontent.com/116558527/198364939-93bfb0ef-7942-4e88-9c48-a5131f76c3a4.jpg)

**Comment by Starlew77** [comment] 2022-10-27 18:12
iv just added more coins but all the nfts have disappeared from wallet aswell :( and i got error code on that nft i just minted :) but is showing in wallet but others have gone i hope i am putting these in right place for you as im not a programmer :( please advise if i should be putting these bugs elsewhere kind regards starlew77  mediastar1977@gmail.com

**Comment by Jordan-Mysten** [comment] 2022-11-03 17:11
Duplicate of #5813.

**Closed by Jordan-Mysten** 2022-11-03 17:11 UTC
