### ISSUE TITLE
Sui Code Bug or Feature Request -  Sui wallet - keepsake 

### ISSUE THREAD

**Issue by Starlew77** [MystenLabs/sui#5680] opened 2022-10-30 12:22 UTC
Listing keepsake https://keepsake.gg/explore?tab=Listings&p=2

Unable to bid or purchase nft form this site ,once highlighted  either bidding or purchase just get a loading cirlcle and nothing happens please see attached photos , 

reported in past regarding nfts - Ethos 2048: An NFT Game this now working fine and all nfts attaching to wallet , thank you :) so far so good managed to get to expert level and all attachments being transfered in sui wallet :)

e.g.
1. Call function <function call>.
2. Use return value and call <other function call>.

## Expected Result

attachment of all purchases to sui wallet from all test games 

e.g.
Expected <other function call> to ret
![20221030_121208](https://user-images.githubusercontent.com/116558527/198878181-0e3470bb-9e7e-49c8-a5b1-ee010ee7bfd0.jpg)
urn 42.

## Actual Result

Specify what the actual unexpected outcome was.

e.g.
<other function call> returned 41.

## System Information

* OS: <specify OS version>
* Compiler: <specify compiler version>
![20221030_121227](https://user-images.githubusercontent.com/116558527/198878207-ea5eb612-713f-4bb9-83ca-044670c5ad10.jpg)

**Comment by Starlew77** [comment] 2022-10-30 12:23
![20221030_121410](https://user-images.githubusercontent.com/116558527/198878223-66fb967a-f0f0-4c1e-ae8a-5774cd5b9ed9.jpg)
 
following previous bugs this seems to working fine all the way to expert level as far as iv got so far :)

**Comment by Jordan-Mysten** [comment] 2022-11-03 17:13
Duplicate of #5690.

**Closed by Jordan-Mysten** 2022-11-03 17:13 UTC
