### ISSUE TITLE
LINKS PROBLEM

### ISSUE THREAD

**Issue by ghodkerupesh** [MystenLabs/sui#7814] opened 2023-01-29 10:27 UTC
we face some problem to find links in laptop and those links are easly found in the mobile app version

**Comment by ghodkerupesh** [comment] 2023-01-29 10:30
solve this one

**Comment by georgescharlesbrain** [comment] 2023-01-30 04:47
Duplicate of https://github.com/MystenLabs/sui/issues/7866

**Closed** 2023-01-30 17:00 UTC
Labels: doc-issue
