### ISSUE TITLE
An error occurred during node synchronization, causing data synchronization failure

### ISSUE THREAD

**Issue by blocknodehub** [MystenLabs/sui#15510] opened 2023-12-31 11:45 UTC
thread '2023-12-31T11:42:38.272350Z ERROR execution_driver{tx_digest=TransactionDigest(DkNocpwm1w8C96EhKx7VdLmRXB5hWdoEcFPJ9fZJriUq)}: telemetry_subscribers: panicked at /home/runner/work/sui/sui/crates/sui-core/src/authority.rs:1829:26:
try_create_dynamic_field_info should not fail.: ObjectSerializationError { error: "Could not find module" } panic.file="/home/runner/work/sui/sui/crates/sui-core/src/authority.rs" panic.line=1829 panic.column=26

**Comment by lcgogo** [comment] 2023-12-31 11:55
same here, version 1.15.1

`2023-12-31T11:30:11.759967Z  INFO sui_node: Sui chain identifier: 35834a8a
2023-12-31T11:30:11.760055Z  INFO sui_node::admin: starting admin server filter=info address=127.0.0.1:1337
thread 'sui-node-runtime' panicked at /sui/sui-mainnet-v1.15.1/crates/sui-core/src/authority.rs:1829:26:
try_create_dynamic_field_info should not fail.: ObjectSerializationError { error: "Could not find module" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-12-31T11:30:14.379635Z ERROR execution_driver{tx_digest=TransactionDigest(DkNocpwm1w8C96EhKx7VdLmRXB5hWdoEcFPJ9fZJriUq)}: telemetry_subscribers: panicked at /sui/sui-mainnet-v1.15.1/crates/sui-core/src/authority.rs:1829:26:
try_create_dynamic_field_info should not fail.: ObjectSerializationError { error: "Could not find module" } panic.file="/sui/sui-mainnet-v1.15.1/crates/sui-core/src/authority.rs" panic.line=1829 panic.column=26
Aborted (core dumped)`

**Comment by claudijd** [comment] 2023-12-31 13:38
I saw some others have this issue, the temporary fix was reverting to commit: b4687afc635738a2c0d66e711c125f4d533cea6f

**Comment by claudijd** [comment] 2023-12-31 16:34
And this issue appears to be a duplicate of #15500

**Comment by yagop** [comment] 2023-12-31 16:37
Same error here

**Comment by zhy827827** [comment] 2023-12-31 18:07
+1

**Comment by stefan-mysten** [comment] 2023-12-31 21:54
Thanks for reporting. This was fixed in ##15501 and it's recommended to update to `sui-v1.15.0-release`.

**Closed by stefan-mysten** 2023-12-31 21:54 UTC

**Comment by blocknodehub** [comment] 2024-01-01 01:01
> Thanks for reporting. This was fixed in ##15501 and it's recommended to update to `sui-v1.15.0-release`.

Which tag does this correspond to

**Comment by stefan-mysten** [comment] 2024-01-01 06:24
I am not sure which tag contains this fix, but I was referring to the release branch: `https://github.com/MystenLabs/sui/tree/releases/sui-v1.15.0-release`
