### ISSUE TITLE
[low gas] Object gets locked if gas is insufficient

### ISSUE THREAD

**Issue by damirka** [MystenLabs/sui#2652] opened 2022-06-22 09:13 UTC
## Steps to Reproduce Issue

Unfortunately, this can not be reproduced with wallet (I need to prepare a test environment in JS):

1. Publish a counter with a Capability. Ie only an owner of a Capability can increase a counter.
2. Try to increment a counter with a low gas setting (in my case `200`)
3. Transaction fails, Capability gets locked. Further actions are impossible.4. 

Code:
```move
module me::locked {
    use sui::transfer;
    use sui::id::VersionedID;
    use sui::tx_context::{Self, TxContext};

    struct SharedBeep has key { id: VersionedID, count: u64 }
    struct OwnedBoop has key { id: VersionedID }

    fun init(ctx: &mut TxContext) {
        transfer::share_object(SharedBeep { id: tx_context::new_id(ctx), count: 0 });
        transfer::transfer(OwnedBoop { id: tx_context::new_id(ctx) }, tx_context::sender(ctx))
    }

    entry fun test(beep: &mut SharedBeep, _boop: &OwnedBoop) {
        beep.count = beep.count + 1;
    }
}
```

## Expected Result

Transaction should fail with insufficient gas but the object shouldn't get locked.

## Actual Result

```
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32000,
        "message": "Error acquiring lock for object(s): [InvalidObjectDigest { object_id: 0xb5aeca9b7cbedcfee0db8a37888495cb29c8e8f0, expected_digest: o#2270deed7cec0bba1b5376a4a4ee764546618b7e69b1cdc10ec2e2d40079c42e }]"
    },
    "id": 1
}
```

If I do the same thing with `wallet`, I get this message:
```
Error calling module: Failure {
    error: "InsufficientGas",
}
```

## System Information

* OS: MacOS
* Compiler: 76eb5aa5dfc265457443e9f1881b77b334e522dd

**Comment by lxfind** [comment] 2022-06-29 02:59
Need steps to reproduce this. Passing back to damir.

**Comment by janetwu11** [comment] 2022-08-15 15:40
Closing this issue as the behavior has changed a fair bit since then. Will open new issues as needed.

**Closed by janetwu11** 2022-08-15 15:40 UTC
Labels: Type: Bug, sui-node
