### ISSUE TITLE
Sui Code Bug or Feature Request

### ISSUE THREAD

**Issue by Favourc** [MystenLabs/sui#7577] opened 2023-01-23 05:09 UTC
I'm glad to be part of this wonderful community of sui. Lately I'm unable to connect my sui to the suia site to claim their suia it just wouldn't connect 🥺 and sui app is becoming slow unlike before

**Comment by georgescharlesbrain** [comment] 2023-01-30 04:55
Duplicate of #7578

**Closed** 2023-05-05 13:17 UTC
