### ISSUE TITLE
Fail to sync with other nodes in Devnet after upgrading to v0.19

### ISSUE THREAD

**Issue by zjshen14** [MystenLabs/sui#6884] opened 2022-12-18 07:11 UTC
## Steps to Reproduce Issue

After upgrading to v0.19, and restart Sui fullnode from scratch

## Expected Result

Fullnode should run successfully

## Actual Result

Fullnode seems not able to connect other peer, logs:

```
2022-12-18T07:07:02.013945Z  WARN rustls::conn: Sending fatal alert BadCertificate    
2022-12-18T07:07:02.016517Z  WARN rustls::conn: Sending fatal alert BadCertificate    
2022-12-18T07:07:02.022979Z  WARN rustls::conn: Sending fatal alert BadCertificate    
2022-12-18T07:07:02.028358Z  WARN rustls::conn: Sending fatal alert BadCertificate    
```

## System Information

* OS: ubuntu 20.04
* Docker image digest: sha256:32ca069dcfa01ce7f070fef46e16236babac7e96c3f0e05de5eca5f2a0288785

**Comment by bmwill** [comment] 2022-12-20 17:01
@zjshen14 Would you happen to have more logs around the time you see those warn statements?

**Comment by zhaoxiangjunupi** [comment] 2022-12-21 06:34
> 

![image](https://user-images.githubusercontent.com/101166067/208837516-0d8c2001-6963-4d13-8540-ee11abbda0a7.png)

**Comment by zjshen14** [comment] 2022-12-21 09:03
> uld you happen to have more logs around the time you see those warn statements?

Unfortunately the old log was purged, what I see in the current log is all "WARN rustls::conn: Sending fatal alert BadCertificate"

**Comment by mattsu2020** [comment] 2022-12-24 14:32
The error was caused by a problem with the genesis file, which I believe was resolved by using the following genesis file.

https://github.com/MystenLabs/sui-genesis/commit/6c993a3354522b2c6bbd2b740ff926b0e3c675f8

**Closed** 2023-01-22 06:25 UTC
