### ISSUE TITLE
Intermittent failure in `submit_transaction_to_consensus` (flacky test?)

### ISSUE THREAD

**Issue by gdanezis** [MystenLabs/sui#1967] opened 2022-05-14 10:06 UTC
I just saw this, in part of the code that I do not really touch:
```
---- consensus_adapter::consensus_tests::submit_transaction_to_consensus stdout ----
2022-05-14T10:01:13.297441Z DEBUG sui_core::transaction_input_checker: Checked locks and found mutable objects num_mutable_objects=1
2022-05-14T10:01:13.308390Z DEBUG sui_core::transaction_input_checker: Checked locks and found mutable objects num_mutable_objects=1
2022-05-14T10:01:13.321656Z DEBUG sui_core::transaction_input_checker: Checked locks and found mutable objects num_mutable_objects=1
2022-05-14T10:01:13.331194Z DEBUG sui_core::transaction_input_checker: Checked locks and found mutable objects num_mutable_objects=1
2022-05-14T10:01:13.346820Z DEBUG process_cert_inner:check_shared_locks: sui_core::authority: Validating shared object sequence numbers from consensus...
2022-05-14T10:01:13.347123Z DEBUG process_cert_inner: sui_core::authority: Read inputs for transaction from DB num_inputs=3
2022-05-14T10:01:13.439317Z DEBUG process_cert_inner:tx_execute_to_effects: sui_core::execution_engine: Finished execution of transaction with status Failure { gas_cost: GasCostSummary { computation_cost: 466, storage_cost: 0, storage_rebate: 0 }, error: InvalidFunctionSignature { error: "Expected 3 arguments calling function 'create', but found 4" } } computation_gas_cost=466 storage_gas_cost=0 storage_gas_rebate=0
thread 'consensus_adapter::consensus_tests::submit_transaction_to_consensus' panicked at 'assertion failed: result.is_ok()', sui_core/src/unit_tests/consensus_tests.rs:194:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    consensus_adapter::consensus_tests::submit_transaction_to_consensus

test result: FAILED. 86 passed; 1 failed; 1 ignored; 0 measured; 0 filtered out; finished in 28.39s
```

**Comment by gdanezis** [comment] 2022-05-14 10:18
Maybe this is the same as:
https://github.com/MystenLabs/sui/issues/1920

**Comment by asonnino** [comment] 2022-05-14 12:00
I can jump in here, I know this part of the codebase. The issue seems related to the grpc network client. I will have a look on Monday

**Comment by asonnino** [comment] 2022-05-16 14:52
Mmh, I don't seem to be able to reproduce the problem:
```bash
while true; do RUST_BACKTRACE=full cargo nextest run  -p sui_core submit_transaction_to_consensus  || break; done
```

Do you still see the issue on the latest main branch? There have been some modifications in  NetworkConfig/AuthorityPrivateInfo that may have disrupted this test (but it should be fixed on main).

**Comment by gdanezis** [comment] 2022-06-06 14:43
Did we fix this at the end?

**Comment by asonnino** [comment] 2022-06-06 14:46
I am not able to reproduce the error anymore and there have been may moving parts since then (eg. the network). So it is probably fixed

**Comment by lxfind** [comment] 2022-06-06 16:18
I still see this on latest main (I am using Mac)

**Closed** 2022-06-06 18:23 UTC
Labels: sui-node
