### ISSUE TITLE
Sui doc content issue or request

### ISSUE THREAD

**Issue by PoojaPagare001** [MystenLabs/sui#7859] opened 2023-01-29 21:34 UTC
Iwe cant find the options for testing in the app after launce of wave 2 on laptop but those options visible in the phone

**Comment by PoojaPagare001** [comment] 2023-01-29 21:34
we cant find the options for testing in the app after launce of wave 2 on laptop but those options visible in the phone

**Comment by georgescharlesbrain** [comment] 2023-01-30 04:31
Duplicate of #7866

**Closed** 2023-01-30 16:58 UTC
Labels: doc-issue
