### ISSUE TITLE
Some error in diagnostic message generated from `move-compiler` 

### ISSUE THREAD

**Issue by hapeeeeee** [MystenLabs/sui#18211] opened 2024-06-12 05:32 UTC
We are developing `sui-move-analyzer` to be compatible with the `2024.beta` version of the Sui Move language, based on the version: (git = "https://github.com/MystenLabs/sui.git", rev = "6e1cf7a1a9971fedd8b7830e586029d6c2cf801a").

We have found that the interface for generating diagnostics (compiler.run::<PASS_HLIR>) seems to have issues. The diagnostic information at this level appears incorrect.
When encountering module provided by Sui itself, an "unexpected name in this position" message appears. For example,  object and tx_context.
![image](https://github.com/MystenLabs/sui/assets/44502668/a9ecd8d0-6de3-4f53-8663-0de231478573)

The diagnostic information only does not appear if the Sui types are explicitly imported using the use statement, such as `use sui::object::ID`, or if `sui::object::ID` and `sui::tx_context::TxContext` are specified when using these types.

**Comment by awelc** [comment] 2024-06-12 07:49
Appears to be caused by the same thing as the problem in https://github.com/MystenLabs/sui/issues/18210

**Comment by cgswords** [comment] 2024-06-18 22:02
Closed as a duplicate of  https://github.com/MystenLabs/sui/issues/18210

**Closed by cgswords** 2024-06-18 22:02 UTC
Labels: move-analyzer
