### ISSUE TITLE
wallet thinks it owns gas objects it doesn't

### ISSUE THREAD

**Issue by mystenmark** [MystenLabs/sui#1552] opened 2022-04-23 00:00 UTC
It appears to be possible for the wallet to think that it still owns objects that it doesn't. Note that `FF46...` still shows up as a gas object, but it has been transferred to a different address.

```
[ marklogan@xxxxxxxxxx ( 4:57PM) ~/dev/sui  <err: 130>2dcc728d ]
; SUI_CONFIG_DIR=/$HOME/.sui/devnet_config ./target/debug/wallet  gas
                Object ID                 |  Version   |  Gas Value
----------------------------------------------------------------------
 37196DE8502E6D80E6A31FBA1A5D6986CC018805 |     0      |   100000
 62635FBA56587074A4349E1882A0C6A09D94BB75 |     0      |   100000
 807F26B4E31A977BA355F8467E006495EC7DE177 |     1      |   100000
 B1AED4DEC3C1E4AF25C9D14021A02BFD7AA1D02E |     2      |    99873
 FF46E294E1E20EE8E9779AA1550B50CB12C9E6CA |     1      |   100000
[ marklogan@adsl-68-251-139-153 ( 4:58PM) ~/dev/sui 2dcc728d ]
;  RUST_LOG="trace" SUI_CONFIG_DIR=/$HOME/.sui/devnet_config ./target/debug/wallet transfer --to E48295E36E20D76E1D6240D32037E75A3787E083  --object-id FF46E294E1E20EE8E9779AA1550B50CB12C9E6CA  --gas B1AED4DEC3C1E4AF25C9D14021A02BFD7AA1D02E --gas-budget 1000
Error: Error acquiring lock for object(s): [IncorrectSigner { error: "Object FF46E294E1E20EE8E9779AA1550B50CB12C9E6CA is owned by account address k#033efbb4d569602e5bd502d4e0f5cba45fc326e4, but signer address is k#3997c1099d2961e09c2a302d8e3644d6ce1237ce" }]
```

**Comment by 666lcz** [comment] 2022-05-10 05:21
Closing due to failing to reproduce

**Closed by 666lcz** 2022-05-10 05:21 UTC
Labels: Type: Bug, tools
